
platform :ios, '8.0'
inhibit_all_warnings! #不显示编译时的警告
def mainPods
	pod 'ReactiveObjC'
    pod 'Realm'
    pod 'AVOSCloud'
    pod 'Reachability', '~> 3.2'
    pod 'AFNetworking'
    pod 'MJRefresh'
end

target 'ObjCDemo' do
	mainPods
end

target 'ObjCDemoTests' do
    mainPods
end




